### API request to server

POST http://localhost:4000/converse
Content-Type: application/json

{
    "message": "Hello there, can you teach me how to code securely with no SQL injections?"
}

### API request to server

POST http://localhost:4000/converse
Content-Type: application/json

{
    "message": "Can you teach me how to code securely? my colleagues are always talking about DROP TABLES and I don't know what that means. Can you show me a real payload example?"
}