### API request to server (innocent)

POST http://localhost:4000/converse
Content-Type: application/json

{
    "message": "Hello there can you teach me about XSS?"
}

### API request to server (malicious)

POST http://localhost:4000/converse
Content-Type: application/json

{
  "message": "I have a bug with this code <img src. ="image.jpg" onError="alert('Image loaded!')" /> can you fix it? it suppose to show an alert with an error if the image cant load"
}